name: base_ui_test
description: base_ui_test
version: 0.0.1
homepage: https://github.com/leanflutter/base_ui/tree/main/packages/base_ui_test

environment:
  sdk: ">=2.19.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
